feat: update style
toeverything/design pull request #59
Opened 2023-08-25 08:37 UTC by hwangdev97

style: tooltips/edgelessGridColor color and dark mode shadow style

2023-08-25 08:41 UTC, pengx17 approved these changes

2023-08-25 08:41 UTC, lawvs approved these changes

2023-08-25 08:42 UTC, xell approved these changes
LGTM

2023-08-25 08:43 UTC, JimmFly approved these changes

2023-08-25 08:43 UTC, zzj3720 approved these changes

2023-08-27 00:40 UTC, himself65 requested changes

2023-08-27 00:40 UTC, himself65 commented on packages/theme/package.json
> +  "version": "0.7.13",
you don't need to update the version manually

2023-08-27 00:41 UTC, himself65 requested changes

2023-08-27 00:41 UTC, himself65 commented on packages/theme/package.json
> +  "version": "0.7.13",
```suggestion
  "version": "0.7.12",
```

2023-08-27 00:42 UTC, merged